### ISSUE TITLE
Error 404 when running the project locally 

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/dsp-web#64]
**Describe the bug**
If you try to locally run AmanRaqami, the home page will throw a 404 error despite the fact that other pages are working just fine. 

**To Reproduce**
1. Run the project locally.
2. Go to http://localhost:[port].
3. The home page will throw a 404 error (although guides and apps are working just fine). 

**Expected behavior**
The home page should work correctly.

**Screenshots**
![Screenshot 2022-02-13 at 02-45-37 404 - أمان رقمي](https://user-images.githubusercontent.com/79845228/153733719-9df36eec-bcee-43c8-8adb-b324da79ec98.png)

**Additional context**
N/A.

**Comment by thread-koder** [comment]
Hello @alsahawneh, hope you are doing great, this issue was caused by issue #63 and it has been fixed, please pull the changes from the development branch and supply the BASE_API_URL environment variable to get it working, if you have any problems I will be happy to help.
